package com.aowin.Model;

import java.awt.Container;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import com.aowin.Listener.JiageListener;
import com.aowin.Listener.JinhuoListener;
import com.aowin.Listener.XiugaiListener;
import com.aowin.Uitls.Goods;
import com.aowin.Uitls.GoodsDao;

public class Guanli {
	public static DefaultTableModel model;
	public static JTable jt;
	public void jiage(int id,String name,int number,double price) {
		String id1=String.valueOf(id);
		String name1=name;
		String number1=String.valueOf(number);
		String price1=String.valueOf(price);
		JFrame jf=new JFrame("商品价格调整");
		jf.setSize(180, 300);
		//jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		Container con=jf.getContentPane();
		con.setLayout(new FlowLayout());
		JLabel jl1=new JLabel("编号");
		con.add(jl1);
		JTextField jtf1=new JTextField(12);
		jtf1.setText(id1);
		jtf1.setEditable(false);
		con.add(jtf1);
		JLabel jl2=new JLabel("商品名");
		con.add(jl2);
		JTextField jtf2=new JTextField(12);
		jtf2.setText(name1);
		jtf2.setEditable(false);
		con.add(jtf2);
		JLabel jl3=new JLabel("进货数量");
		con.add(jl3);
		JTextField jtf3=new JTextField(12);
		jtf3.setText(number1);
		jtf3.setEditable(false);
		con.add(jtf3);
		JLabel jl4=new JLabel("价格");
		con.add(jl4);
		JTextField jtf4=new JTextField(12);
		jtf4.setText(price1);
		con.add(jtf4);
		JButton jb1=new JButton("确认调整价格");
		con.add(jb1);
		jf.setVisible(true);
		JiageListener jgl=new JiageListener(jf, jtf4);
		jb1.addActionListener(jgl);
	}
	public void xiugai(int id,String name,int number,double price) {
		String id1=String.valueOf(id);
		String name1=name;
		String number1=String.valueOf(number);
		String price1=String.valueOf(price);
		JFrame jf=new JFrame("商品修改");
		jf.setSize(180, 300);
		//jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		Container con=jf.getContentPane();
		con.setLayout(new FlowLayout());
		JLabel jl1=new JLabel("编号");
		con.add(jl1);
		JTextField jtf1=new JTextField(12);
		jtf1.setText(id1);
		jtf1.setEditable(false);
		con.add(jtf1);
		JLabel jl2=new JLabel("商品名");
		con.add(jl2);
		JTextField jtf2=new JTextField(12);
		jtf2.setText(name1);
		con.add(jtf2);
		JLabel jl3=new JLabel("进货数量");
		con.add(jl3);
		JTextField jtf3=new JTextField(12);
		jtf3.setText(number1);
		jtf3.setEditable(false);
		con.add(jtf3);
		JLabel jl4=new JLabel("价格");
		con.add(jl4);
		JTextField jtf4=new JTextField(12);
		jtf4.setText(price1);
		jtf4.setEditable(false);
		con.add(jtf4);
		JButton jb1=new JButton("确认修改");
		con.add(jb1);
		jf.setVisible(true);
		XiugaiListener xhl=new XiugaiListener(jf, jtf2);
		jb1.addActionListener(xhl);
	}
	public void jinhuo(int id,String name,int number,double price) {
		String id1=String.valueOf(id);
		String name1=name;
		String number1=String.valueOf(number);
		String price1=String.valueOf(price);
		JFrame jf=new JFrame("商品进货");
		jf.setSize(180, 300);
		//jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		Container con=jf.getContentPane();
		con.setLayout(new FlowLayout());
		JLabel jl1=new JLabel("编号");
		con.add(jl1);
		JTextField jtf1=new JTextField(12);
		jtf1.setText(id1);
		jtf1.setEditable(false);
		con.add(jtf1);
		JLabel jl2=new JLabel("商品名");
		con.add(jl2);
		JTextField jtf2=new JTextField(12);
		jtf2.setText(name1);
		jtf2.setEditable(false);
		con.add(jtf2);
		JLabel jl3=new JLabel("进货数量");
		con.add(jl3);
		JTextField jtf3=new JTextField(12);
		jtf3.setText("");
		con.add(jtf3);
		JLabel jl4=new JLabel("价格");
		con.add(jl4);
		JTextField jtf4=new JTextField(12);
		jtf4.setText(price1);
		jtf4.setEditable(false);
		con.add(jtf4);
		JButton jb1=new JButton("确认进货");
		con.add(jb1);
		jf.setVisible(true);
		JinhuoListener jhl1=new JinhuoListener(jf,jtf3);
		jb1.addActionListener(jhl1);
	}
	public void build() throws SQLException {
		JFrame jf=new JFrame("欢迎来到用户操作界面！");
		jf.setSize(500, 600);
		jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		Container con=jf.getContentPane();
		con.setLayout(new FlowLayout());
		JLabel jl1=new JLabel("商品管理系统");
		con.add(jl1);
		Object []o= {"编号","商品名","数量","价格"};
		model=new DefaultTableModel(o,0);
		jt=new JTable(model);
		JScrollPane js=new JScrollPane(jt);
		con.add(js);
		JButton jb1=new JButton("进货");
		con.add(jb1);
		JButton jb2=new JButton("修改商品名");
		con.add(jb2);
		JButton jb3=new JButton("价格调整");
		con.add(jb3);
		jf.setVisible(true);
		JinhuoListener jhl=new JinhuoListener(model,jt);
		XiugaiListener xgl=new XiugaiListener(model, jt);
		JiageListener jgl=new JiageListener(model, jt);
		jb2.addActionListener(xgl);
		jb1.addActionListener(jhl);
		jb3.addActionListener(jgl);
		GoodsDao gd=new GoodsDao();
		ArrayList<Goods> al=gd.selectAll();
		for(int i=0;i<al.size();i++) {
			Goods g=al.get(i);
			int id=g.getId();
			String name=g.getName();
			int number=g.getNum();
			double price=g.getPrice();
			Object row[] ={id,name,number,price};
			model.addRow(row);
		}
}
}