server:
  port: 8088
  servlet:
    context-path: /SpringBoot
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616

mybatis:
  type-aliases-package: com.aowin.model
  mapper-locations:
   - classpath:/mapper/*.xml
   